//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErasEasyLife.Student {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Studente", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Studente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdStudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_nField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instagramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazionalitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdStud {
            get {
                return this.IdStudField;
            }
            set {
                if ((this.IdStudField.Equals(value) != true)) {
                    this.IdStudField = value;
                    this.RaisePropertyChanged("IdStud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_n {
            get {
                return this.data_nField;
            }
            set {
                if ((object.ReferenceEquals(this.data_nField, value) != true)) {
                    this.data_nField = value;
                    this.RaisePropertyChanged("data_n");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facebook {
            get {
                return this.facebookField;
            }
            set {
                if ((object.ReferenceEquals(this.facebookField, value) != true)) {
                    this.facebookField = value;
                    this.RaisePropertyChanged("facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instagram {
            get {
                return this.instagramField;
            }
            set {
                if ((object.ReferenceEquals(this.instagramField, value) != true)) {
                    this.instagramField = value;
                    this.RaisePropertyChanged("instagram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazionalita {
            get {
                return this.nazionalitaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazionalitaField, value) != true)) {
                    this.nazionalitaField = value;
                    this.RaisePropertyChanged("nazionalita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Svolgimento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Svolgimento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_iField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Student.Evento eventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Student.Luogo luogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_iField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_f {
            get {
                return this.data_fField;
            }
            set {
                if ((object.ReferenceEquals(this.data_fField, value) != true)) {
                    this.data_fField = value;
                    this.RaisePropertyChanged("data_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_i {
            get {
                return this.data_iField;
            }
            set {
                if ((object.ReferenceEquals(this.data_iField, value) != true)) {
                    this.data_iField = value;
                    this.RaisePropertyChanged("data_i");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Student.Evento evento {
            get {
                return this.eventoField;
            }
            set {
                if ((object.ReferenceEquals(this.eventoField, value) != true)) {
                    this.eventoField = value;
                    this.RaisePropertyChanged("evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Student.Luogo luogo {
            get {
                return this.luogoField;
            }
            set {
                if ((object.ReferenceEquals(this.luogoField, value) != true)) {
                    this.luogoField = value;
                    this.RaisePropertyChanged("luogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_f {
            get {
                return this.ora_fField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_fField, value) != true)) {
                    this.ora_fField = value;
                    this.RaisePropertyChanged("ora_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_i {
            get {
                return this.ora_iField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_iField, value) != true)) {
                    this.ora_iField = value;
                    this.RaisePropertyChanged("ora_i");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Evento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Student.Associazione assField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEv {
            get {
                return this.IdEvField;
            }
            set {
                if ((this.IdEvField.Equals(value) != true)) {
                    this.IdEvField = value;
                    this.RaisePropertyChanged("IdEv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Student.Associazione ass {
            get {
                return this.assField;
            }
            set {
                if ((object.ReferenceEquals(this.assField, value) != true)) {
                    this.assField = value;
                    this.RaisePropertyChanged("ass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.descrizioneField, value) != true)) {
                    this.descrizioneField = value;
                    this.RaisePropertyChanged("descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_p {
            get {
                return this.max_pField;
            }
            set {
                if ((this.max_pField.Equals(value) != true)) {
                    this.max_pField = value;
                    this.RaisePropertyChanged("max_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_v {
            get {
                return this.max_vField;
            }
            set {
                if ((this.max_vField.Equals(value) != true)) {
                    this.max_vField = value;
                    this.RaisePropertyChanged("max_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_p {
            get {
                return this.min_pField;
            }
            set {
                if ((this.min_pField.Equals(value) != true)) {
                    this.min_pField = value;
                    this.RaisePropertyChanged("min_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_v {
            get {
                return this.min_vField;
            }
            set {
                if ((this.min_vField.Equals(value) != true)) {
                    this.min_vField = value;
                    this.RaisePropertyChanged("min_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipologia {
            get {
                return this.tipologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipologiaField, value) != true)) {
                    this.tipologiaField = value;
                    this.RaisePropertyChanged("tipologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Luogo", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Luogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLuogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLuogo {
            get {
                return this.IdLuogoField;
            }
            set {
                if ((this.IdLuogoField.Equals(value) != true)) {
                    this.IdLuogoField = value;
                    this.RaisePropertyChanged("IdLuogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associazione", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf")]
    [System.SerializableAttribute()]
    public partial class Associazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAss {
            get {
                return this.IdAssField;
            }
            set {
                if ((this.IdAssField.Equals(value) != true)) {
                    this.IdAssField = value;
                    this.RaisePropertyChanged("IdAss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Student.IStudent")]
    public interface IStudent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Registration", ReplyAction="http://tempuri.org/IStudent/RegistrationResponse")]
        bool Registration(ErasEasyLife.Student.Studente s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Registration", ReplyAction="http://tempuri.org/IStudent/RegistrationResponse")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Student.Studente s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Login", ReplyAction="http://tempuri.org/IStudent/LoginResponse")]
        ErasEasyLife.Student.Studente Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Login", ReplyAction="http://tempuri.org/IStudent/LoginResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Student.Studente> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Profile", ReplyAction="http://tempuri.org/IStudent/ProfileResponse")]
        ErasEasyLife.Student.Studente Profile(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Profile", ReplyAction="http://tempuri.org/IStudent/ProfileResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Student.Studente> ProfileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/UpdateProfile", ReplyAction="http://tempuri.org/IStudent/UpdateProfileResponse")]
        bool UpdateProfile(ErasEasyLife.Student.Studente a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/UpdateProfile", ReplyAction="http://tempuri.org/IStudent/UpdateProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Student.Studente a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/UpdatePassword", ReplyAction="http://tempuri.org/IStudent/UpdatePasswordResponse")]
        bool UpdatePassword(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/UpdatePassword", ReplyAction="http://tempuri.org/IStudent/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Show_students", ReplyAction="http://tempuri.org/IStudent/Show_studentsResponse")]
        ErasEasyLife.Student.Studente[] Show_students(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Show_students", ReplyAction="http://tempuri.org/IStudent/Show_studentsResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Student.Studente[]> Show_studentsAsync(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/BookEvent", ReplyAction="http://tempuri.org/IStudent/BookEventResponse")]
        bool BookEvent(int studente, int evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/BookEvent", ReplyAction="http://tempuri.org/IStudent/BookEventResponse")]
        System.Threading.Tasks.Task<bool> BookEventAsync(int studente, int evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Show_Event", ReplyAction="http://tempuri.org/IStudent/Show_EventResponse")]
        ErasEasyLife.Student.Svolgimento[] Show_Event(int idstud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Show_Event", ReplyAction="http://tempuri.org/IStudent/Show_EventResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Student.Svolgimento[]> Show_EventAsync(int idstud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/CancelBooking", ReplyAction="http://tempuri.org/IStudent/CancelBookingResponse")]
        bool CancelBooking(int studente, int evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/CancelBooking", ReplyAction="http://tempuri.org/IStudent/CancelBookingResponse")]
        System.Threading.Tasks.Task<bool> CancelBookingAsync(int studente, int evento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentChannel : ErasEasyLife.Student.IStudent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentClient : System.ServiceModel.ClientBase<ErasEasyLife.Student.IStudent>, ErasEasyLife.Student.IStudent {
        
        public StudentClient() {
        }
        
        public StudentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registration(ErasEasyLife.Student.Studente s) {
            return base.Channel.Registration(s);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Student.Studente s) {
            return base.Channel.RegistrationAsync(s);
        }
        
        public ErasEasyLife.Student.Studente Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Student.Studente> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public ErasEasyLife.Student.Studente Profile(int id) {
            return base.Channel.Profile(id);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Student.Studente> ProfileAsync(int id) {
            return base.Channel.ProfileAsync(id);
        }
        
        public bool UpdateProfile(ErasEasyLife.Student.Studente a) {
            return base.Channel.UpdateProfile(a);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Student.Studente a) {
            return base.Channel.UpdateProfileAsync(a);
        }
        
        public bool UpdatePassword(int id, string new_password) {
            return base.Channel.UpdatePassword(id, new_password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password) {
            return base.Channel.UpdatePasswordAsync(id, new_password);
        }
        
        public ErasEasyLife.Student.Studente[] Show_students(string cond) {
            return base.Channel.Show_students(cond);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Student.Studente[]> Show_studentsAsync(string cond) {
            return base.Channel.Show_studentsAsync(cond);
        }
        
        public bool BookEvent(int studente, int evento) {
            return base.Channel.BookEvent(studente, evento);
        }
        
        public System.Threading.Tasks.Task<bool> BookEventAsync(int studente, int evento) {
            return base.Channel.BookEventAsync(studente, evento);
        }
        
        public ErasEasyLife.Student.Svolgimento[] Show_Event(int idstud) {
            return base.Channel.Show_Event(idstud);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Student.Svolgimento[]> Show_EventAsync(int idstud) {
            return base.Channel.Show_EventAsync(idstud);
        }
        
        public bool CancelBooking(int studente, int evento) {
            return base.Channel.CancelBooking(studente, evento);
        }
        
        public System.Threading.Tasks.Task<bool> CancelBookingAsync(int studente, int evento) {
            return base.Channel.CancelBookingAsync(studente, evento);
        }
    }
}
