//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErasEasyLife.Volunteer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Volontario", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf")]
    [System.SerializableAttribute()]
    public partial class Volontario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVolontField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Volunteer.Associazione assField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_iscrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_nField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ruoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVolont {
            get {
                return this.IdVolontField;
            }
            set {
                if ((this.IdVolontField.Equals(value) != true)) {
                    this.IdVolontField = value;
                    this.RaisePropertyChanged("IdVolont");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Volunteer.Associazione ass {
            get {
                return this.assField;
            }
            set {
                if ((object.ReferenceEquals(this.assField, value) != true)) {
                    this.assField = value;
                    this.RaisePropertyChanged("ass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_iscr {
            get {
                return this.data_iscrField;
            }
            set {
                if ((object.ReferenceEquals(this.data_iscrField, value) != true)) {
                    this.data_iscrField = value;
                    this.RaisePropertyChanged("data_iscr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_n {
            get {
                return this.data_nField;
            }
            set {
                if ((object.ReferenceEquals(this.data_nField, value) != true)) {
                    this.data_nField = value;
                    this.RaisePropertyChanged("data_n");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruolo {
            get {
                return this.ruoloField;
            }
            set {
                if ((object.ReferenceEquals(this.ruoloField, value) != true)) {
                    this.ruoloField = value;
                    this.RaisePropertyChanged("ruolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associazione", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf")]
    [System.SerializableAttribute()]
    public partial class Associazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAss {
            get {
                return this.IdAssField;
            }
            set {
                if ((this.IdAssField.Equals(value) != true)) {
                    this.IdAssField = value;
                    this.RaisePropertyChanged("IdAss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Svolgimento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Svolgimento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_iField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Volunteer.Evento eventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Volunteer.Luogo luogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_iField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_f {
            get {
                return this.data_fField;
            }
            set {
                if ((object.ReferenceEquals(this.data_fField, value) != true)) {
                    this.data_fField = value;
                    this.RaisePropertyChanged("data_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_i {
            get {
                return this.data_iField;
            }
            set {
                if ((object.ReferenceEquals(this.data_iField, value) != true)) {
                    this.data_iField = value;
                    this.RaisePropertyChanged("data_i");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Volunteer.Evento evento {
            get {
                return this.eventoField;
            }
            set {
                if ((object.ReferenceEquals(this.eventoField, value) != true)) {
                    this.eventoField = value;
                    this.RaisePropertyChanged("evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Volunteer.Luogo luogo {
            get {
                return this.luogoField;
            }
            set {
                if ((object.ReferenceEquals(this.luogoField, value) != true)) {
                    this.luogoField = value;
                    this.RaisePropertyChanged("luogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_f {
            get {
                return this.ora_fField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_fField, value) != true)) {
                    this.ora_fField = value;
                    this.RaisePropertyChanged("ora_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_i {
            get {
                return this.ora_iField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_iField, value) != true)) {
                    this.ora_iField = value;
                    this.RaisePropertyChanged("ora_i");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Evento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Volunteer.Associazione assField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEv {
            get {
                return this.IdEvField;
            }
            set {
                if ((this.IdEvField.Equals(value) != true)) {
                    this.IdEvField = value;
                    this.RaisePropertyChanged("IdEv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Volunteer.Associazione ass {
            get {
                return this.assField;
            }
            set {
                if ((object.ReferenceEquals(this.assField, value) != true)) {
                    this.assField = value;
                    this.RaisePropertyChanged("ass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.descrizioneField, value) != true)) {
                    this.descrizioneField = value;
                    this.RaisePropertyChanged("descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_p {
            get {
                return this.max_pField;
            }
            set {
                if ((this.max_pField.Equals(value) != true)) {
                    this.max_pField = value;
                    this.RaisePropertyChanged("max_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_v {
            get {
                return this.max_vField;
            }
            set {
                if ((this.max_vField.Equals(value) != true)) {
                    this.max_vField = value;
                    this.RaisePropertyChanged("max_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_p {
            get {
                return this.min_pField;
            }
            set {
                if ((this.min_pField.Equals(value) != true)) {
                    this.min_pField = value;
                    this.RaisePropertyChanged("min_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_v {
            get {
                return this.min_vField;
            }
            set {
                if ((this.min_vField.Equals(value) != true)) {
                    this.min_vField = value;
                    this.RaisePropertyChanged("min_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipologia {
            get {
                return this.tipologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipologiaField, value) != true)) {
                    this.tipologiaField = value;
                    this.RaisePropertyChanged("tipologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Luogo", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Luogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLuogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLuogo {
            get {
                return this.IdLuogoField;
            }
            set {
                if ((this.IdLuogoField.Equals(value) != true)) {
                    this.IdLuogoField = value;
                    this.RaisePropertyChanged("IdLuogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Volunteer.IVolunteer")]
    public interface IVolunteer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Registration", ReplyAction="http://tempuri.org/IVolunteer/RegistrationResponse")]
        bool Registration(ErasEasyLife.Volunteer.Volontario v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Registration", ReplyAction="http://tempuri.org/IVolunteer/RegistrationResponse")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Volunteer.Volontario v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Login", ReplyAction="http://tempuri.org/IVolunteer/LoginResponse")]
        ErasEasyLife.Volunteer.Volontario Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Login", ReplyAction="http://tempuri.org/IVolunteer/LoginResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Volontario> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Profile", ReplyAction="http://tempuri.org/IVolunteer/ProfileResponse")]
        ErasEasyLife.Volunteer.Volontario Profile(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Profile", ReplyAction="http://tempuri.org/IVolunteer/ProfileResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Volontario> ProfileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/UpdateProfile", ReplyAction="http://tempuri.org/IVolunteer/UpdateProfileResponse")]
        bool UpdateProfile(ErasEasyLife.Volunteer.Volontario v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/UpdateProfile", ReplyAction="http://tempuri.org/IVolunteer/UpdateProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Volunteer.Volontario v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/UpdatePassword", ReplyAction="http://tempuri.org/IVolunteer/UpdatePasswordResponse")]
        bool UpdatePassword(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/UpdatePassword", ReplyAction="http://tempuri.org/IVolunteer/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/GetAssociazione", ReplyAction="http://tempuri.org/IVolunteer/GetAssociazioneResponse")]
        ErasEasyLife.Volunteer.Associazione GetAssociazione(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/GetAssociazione", ReplyAction="http://tempuri.org/IVolunteer/GetAssociazioneResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Associazione> GetAssociazioneAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Show_volontari", ReplyAction="http://tempuri.org/IVolunteer/Show_volontariResponse")]
        ErasEasyLife.Volunteer.Volontario[] Show_volontari(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Show_volontari", ReplyAction="http://tempuri.org/IVolunteer/Show_volontariResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Volontario[]> Show_volontariAsync(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/BookEvent", ReplyAction="http://tempuri.org/IVolunteer/BookEventResponse")]
        bool BookEvent(int volontario, int evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/BookEvent", ReplyAction="http://tempuri.org/IVolunteer/BookEventResponse")]
        System.Threading.Tasks.Task<bool> BookEventAsync(int volontario, int evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Show_Event", ReplyAction="http://tempuri.org/IVolunteer/Show_EventResponse")]
        ErasEasyLife.Volunteer.Svolgimento[] Show_Event(int idvol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/Show_Event", ReplyAction="http://tempuri.org/IVolunteer/Show_EventResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Svolgimento[]> Show_EventAsync(int idvol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/CancelBooking", ReplyAction="http://tempuri.org/IVolunteer/CancelBookingResponse")]
        bool CancelBooking(int volontario, int evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolunteer/CancelBooking", ReplyAction="http://tempuri.org/IVolunteer/CancelBookingResponse")]
        System.Threading.Tasks.Task<bool> CancelBookingAsync(int volontario, int evento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVolunteerChannel : ErasEasyLife.Volunteer.IVolunteer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VolunteerClient : System.ServiceModel.ClientBase<ErasEasyLife.Volunteer.IVolunteer>, ErasEasyLife.Volunteer.IVolunteer {
        
        public VolunteerClient() {
        }
        
        public VolunteerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VolunteerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VolunteerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VolunteerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registration(ErasEasyLife.Volunteer.Volontario v) {
            return base.Channel.Registration(v);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Volunteer.Volontario v) {
            return base.Channel.RegistrationAsync(v);
        }
        
        public ErasEasyLife.Volunteer.Volontario Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Volontario> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public ErasEasyLife.Volunteer.Volontario Profile(int id) {
            return base.Channel.Profile(id);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Volontario> ProfileAsync(int id) {
            return base.Channel.ProfileAsync(id);
        }
        
        public bool UpdateProfile(ErasEasyLife.Volunteer.Volontario v) {
            return base.Channel.UpdateProfile(v);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Volunteer.Volontario v) {
            return base.Channel.UpdateProfileAsync(v);
        }
        
        public bool UpdatePassword(int id, string new_password) {
            return base.Channel.UpdatePassword(id, new_password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password) {
            return base.Channel.UpdatePasswordAsync(id, new_password);
        }
        
        public ErasEasyLife.Volunteer.Associazione GetAssociazione(int id) {
            return base.Channel.GetAssociazione(id);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Associazione> GetAssociazioneAsync(int id) {
            return base.Channel.GetAssociazioneAsync(id);
        }
        
        public ErasEasyLife.Volunteer.Volontario[] Show_volontari(string cond) {
            return base.Channel.Show_volontari(cond);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Volontario[]> Show_volontariAsync(string cond) {
            return base.Channel.Show_volontariAsync(cond);
        }
        
        public bool BookEvent(int volontario, int evento) {
            return base.Channel.BookEvent(volontario, evento);
        }
        
        public System.Threading.Tasks.Task<bool> BookEventAsync(int volontario, int evento) {
            return base.Channel.BookEventAsync(volontario, evento);
        }
        
        public ErasEasyLife.Volunteer.Svolgimento[] Show_Event(int idvol) {
            return base.Channel.Show_Event(idvol);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Volunteer.Svolgimento[]> Show_EventAsync(int idvol) {
            return base.Channel.Show_EventAsync(idvol);
        }
        
        public bool CancelBooking(int volontario, int evento) {
            return base.Channel.CancelBooking(volontario, evento);
        }
        
        public System.Threading.Tasks.Task<bool> CancelBookingAsync(int volontario, int evento) {
            return base.Channel.CancelBookingAsync(volontario, evento);
        }
    }
}
