//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErasEasyLife.Association {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associazione", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Associazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAss {
            get {
                return this.IdAssField;
            }
            set {
                if ((this.IdAssField.Equals(value) != true)) {
                    this.IdAssField = value;
                    this.RaisePropertyChanged("IdAss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Svolgimento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Svolgimento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_iField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Association.Evento eventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Association.Luogo luogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_iField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_f {
            get {
                return this.data_fField;
            }
            set {
                if ((object.ReferenceEquals(this.data_fField, value) != true)) {
                    this.data_fField = value;
                    this.RaisePropertyChanged("data_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_i {
            get {
                return this.data_iField;
            }
            set {
                if ((object.ReferenceEquals(this.data_iField, value) != true)) {
                    this.data_iField = value;
                    this.RaisePropertyChanged("data_i");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Association.Evento evento {
            get {
                return this.eventoField;
            }
            set {
                if ((object.ReferenceEquals(this.eventoField, value) != true)) {
                    this.eventoField = value;
                    this.RaisePropertyChanged("evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Association.Luogo luogo {
            get {
                return this.luogoField;
            }
            set {
                if ((object.ReferenceEquals(this.luogoField, value) != true)) {
                    this.luogoField = value;
                    this.RaisePropertyChanged("luogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_f {
            get {
                return this.ora_fField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_fField, value) != true)) {
                    this.ora_fField = value;
                    this.RaisePropertyChanged("ora_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_i {
            get {
                return this.ora_iField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_iField, value) != true)) {
                    this.ora_iField = value;
                    this.RaisePropertyChanged("ora_i");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Evento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Association.Associazione assField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEv {
            get {
                return this.IdEvField;
            }
            set {
                if ((this.IdEvField.Equals(value) != true)) {
                    this.IdEvField = value;
                    this.RaisePropertyChanged("IdEv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Association.Associazione ass {
            get {
                return this.assField;
            }
            set {
                if ((object.ReferenceEquals(this.assField, value) != true)) {
                    this.assField = value;
                    this.RaisePropertyChanged("ass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.descrizioneField, value) != true)) {
                    this.descrizioneField = value;
                    this.RaisePropertyChanged("descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_p {
            get {
                return this.max_pField;
            }
            set {
                if ((this.max_pField.Equals(value) != true)) {
                    this.max_pField = value;
                    this.RaisePropertyChanged("max_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_v {
            get {
                return this.max_vField;
            }
            set {
                if ((this.max_vField.Equals(value) != true)) {
                    this.max_vField = value;
                    this.RaisePropertyChanged("max_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_p {
            get {
                return this.min_pField;
            }
            set {
                if ((this.min_pField.Equals(value) != true)) {
                    this.min_pField = value;
                    this.RaisePropertyChanged("min_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_v {
            get {
                return this.min_vField;
            }
            set {
                if ((this.min_vField.Equals(value) != true)) {
                    this.min_vField = value;
                    this.RaisePropertyChanged("min_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipologia {
            get {
                return this.tipologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipologiaField, value) != true)) {
                    this.tipologiaField = value;
                    this.RaisePropertyChanged("tipologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Luogo", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Luogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLuogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLuogo {
            get {
                return this.IdLuogoField;
            }
            set {
                if ((this.IdLuogoField.Equals(value) != true)) {
                    this.IdLuogoField = value;
                    this.RaisePropertyChanged("IdLuogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Association.IAssociation")]
    public interface IAssociation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Registration", ReplyAction="http://tempuri.org/IAssociation/RegistrationResponse")]
        bool Registration(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Registration", ReplyAction="http://tempuri.org/IAssociation/RegistrationResponse")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Login", ReplyAction="http://tempuri.org/IAssociation/LoginResponse")]
        ErasEasyLife.Association.Associazione Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Login", ReplyAction="http://tempuri.org/IAssociation/LoginResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Profile", ReplyAction="http://tempuri.org/IAssociation/ProfileResponse")]
        ErasEasyLife.Association.Associazione Profile(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Profile", ReplyAction="http://tempuri.org/IAssociation/ProfileResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> ProfileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdateProfile", ReplyAction="http://tempuri.org/IAssociation/UpdateProfileResponse")]
        bool UpdateProfile(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdateProfile", ReplyAction="http://tempuri.org/IAssociation/UpdateProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdatePassword", ReplyAction="http://tempuri.org/IAssociation/UpdatePasswordResponse")]
        bool UpdatePassword(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdatePassword", ReplyAction="http://tempuri.org/IAssociation/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Create_events", ReplyAction="http://tempuri.org/IAssociation/Create_eventsResponse")]
        bool Create_events(ErasEasyLife.Association.Svolgimento s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Create_events", ReplyAction="http://tempuri.org/IAssociation/Create_eventsResponse")]
        System.Threading.Tasks.Task<bool> Create_eventsAsync(ErasEasyLife.Association.Svolgimento s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/GetCitta", ReplyAction="http://tempuri.org/IAssociation/GetCittaResponse")]
        string[] GetCitta(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/GetCitta", ReplyAction="http://tempuri.org/IAssociation/GetCittaResponse")]
        System.Threading.Tasks.Task<string[]> GetCittaAsync(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Show_associations", ReplyAction="http://tempuri.org/IAssociation/Show_associationsResponse")]
        ErasEasyLife.Association.Associazione[] Show_associations(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Show_associations", ReplyAction="http://tempuri.org/IAssociation/Show_associationsResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione[]> Show_associationsAsync(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Show_Event", ReplyAction="http://tempuri.org/IAssociation/Show_EventResponse")]
        ErasEasyLife.Association.Svolgimento[] Show_Event(int idass, string tipologia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Show_Event", ReplyAction="http://tempuri.org/IAssociation/Show_EventResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Association.Svolgimento[]> Show_EventAsync(int idass, string tipologia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/add_ruolo", ReplyAction="http://tempuri.org/IAssociation/add_ruoloResponse")]
        bool add_ruolo(int idvolont, string ruolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/add_ruolo", ReplyAction="http://tempuri.org/IAssociation/add_ruoloResponse")]
        System.Threading.Tasks.Task<bool> add_ruoloAsync(int idvolont, string ruolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Generate_id", ReplyAction="http://tempuri.org/IAssociation/Generate_idResponse")]
        int Generate_id();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Generate_id", ReplyAction="http://tempuri.org/IAssociation/Generate_idResponse")]
        System.Threading.Tasks.Task<int> Generate_idAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssociationChannel : ErasEasyLife.Association.IAssociation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssociationClient : System.ServiceModel.ClientBase<ErasEasyLife.Association.IAssociation>, ErasEasyLife.Association.IAssociation {
        
        public AssociationClient() {
        }
        
        public AssociationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssociationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssociationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssociationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registration(ErasEasyLife.Association.Associazione a) {
            return base.Channel.Registration(a);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Association.Associazione a) {
            return base.Channel.RegistrationAsync(a);
        }
        
        public ErasEasyLife.Association.Associazione Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public ErasEasyLife.Association.Associazione Profile(int id) {
            return base.Channel.Profile(id);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> ProfileAsync(int id) {
            return base.Channel.ProfileAsync(id);
        }
        
        public bool UpdateProfile(ErasEasyLife.Association.Associazione a) {
            return base.Channel.UpdateProfile(a);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Association.Associazione a) {
            return base.Channel.UpdateProfileAsync(a);
        }
        
        public bool UpdatePassword(int id, string new_password) {
            return base.Channel.UpdatePassword(id, new_password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password) {
            return base.Channel.UpdatePasswordAsync(id, new_password);
        }
        
        public bool Create_events(ErasEasyLife.Association.Svolgimento s) {
            return base.Channel.Create_events(s);
        }
        
        public System.Threading.Tasks.Task<bool> Create_eventsAsync(ErasEasyLife.Association.Svolgimento s) {
            return base.Channel.Create_eventsAsync(s);
        }
        
        public string[] GetCitta(string cond) {
            return base.Channel.GetCitta(cond);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCittaAsync(string cond) {
            return base.Channel.GetCittaAsync(cond);
        }
        
        public ErasEasyLife.Association.Associazione[] Show_associations(string cond) {
            return base.Channel.Show_associations(cond);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione[]> Show_associationsAsync(string cond) {
            return base.Channel.Show_associationsAsync(cond);
        }
        
        public ErasEasyLife.Association.Svolgimento[] Show_Event(int idass, string tipologia) {
            return base.Channel.Show_Event(idass, tipologia);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Association.Svolgimento[]> Show_EventAsync(int idass, string tipologia) {
            return base.Channel.Show_EventAsync(idass, tipologia);
        }
        
        public bool add_ruolo(int idvolont, string ruolo) {
            return base.Channel.add_ruolo(idvolont, ruolo);
        }
        
        public System.Threading.Tasks.Task<bool> add_ruoloAsync(int idvolont, string ruolo) {
            return base.Channel.add_ruoloAsync(idvolont, ruolo);
        }
        
        public int Generate_id() {
            return base.Channel.Generate_id();
        }
        
        public System.Threading.Tasks.Task<int> Generate_idAsync() {
            return base.Channel.Generate_idAsync();
        }
    }
}
