//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErasEasyLife.Association {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associazione", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf")]
    [System.SerializableAttribute()]
    public partial class Associazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAss {
            get {
                return this.IdAssField;
            }
            set {
                if ((this.IdAssField.Equals(value) != true)) {
                    this.IdAssField = value;
                    this.RaisePropertyChanged("IdAss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Association.IAssociation")]
    public interface IAssociation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Registration", ReplyAction="http://tempuri.org/IAssociation/RegistrationResponse")]
        bool Registration(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Registration", ReplyAction="http://tempuri.org/IAssociation/RegistrationResponse")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Login", ReplyAction="http://tempuri.org/IAssociation/LoginResponse")]
        ErasEasyLife.Association.Associazione Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Login", ReplyAction="http://tempuri.org/IAssociation/LoginResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Profile", ReplyAction="http://tempuri.org/IAssociation/ProfileResponse")]
        ErasEasyLife.Association.Associazione Profile(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/Profile", ReplyAction="http://tempuri.org/IAssociation/ProfileResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> ProfileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdateProfile", ReplyAction="http://tempuri.org/IAssociation/UpdateProfileResponse")]
        bool UpdateProfile(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdateProfile", ReplyAction="http://tempuri.org/IAssociation/UpdateProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Association.Associazione a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdatePassword", ReplyAction="http://tempuri.org/IAssociation/UpdatePasswordResponse")]
        bool UpdatePassword(int id, string new_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssociation/UpdatePassword", ReplyAction="http://tempuri.org/IAssociation/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssociationChannel : ErasEasyLife.Association.IAssociation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssociationClient : System.ServiceModel.ClientBase<ErasEasyLife.Association.IAssociation>, ErasEasyLife.Association.IAssociation {
        
        public AssociationClient() {
        }
        
        public AssociationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssociationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssociationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssociationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registration(ErasEasyLife.Association.Associazione a) {
            return base.Channel.Registration(a);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(ErasEasyLife.Association.Associazione a) {
            return base.Channel.RegistrationAsync(a);
        }
        
        public ErasEasyLife.Association.Associazione Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public ErasEasyLife.Association.Associazione Profile(int id) {
            return base.Channel.Profile(id);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Association.Associazione> ProfileAsync(int id) {
            return base.Channel.ProfileAsync(id);
        }
        
        public bool UpdateProfile(ErasEasyLife.Association.Associazione a) {
            return base.Channel.UpdateProfile(a);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProfileAsync(ErasEasyLife.Association.Associazione a) {
            return base.Channel.UpdateProfileAsync(a);
        }
        
        public bool UpdatePassword(int id, string new_password) {
            return base.Channel.UpdatePassword(id, new_password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(int id, string new_password) {
            return base.Channel.UpdatePasswordAsync(id, new_password);
        }
    }
}
