//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErasEasyLife.Event {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Svolgimento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Svolgimento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_iField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Event.Evento eventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Event.Luogo luogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_fField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ora_iField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_f {
            get {
                return this.data_fField;
            }
            set {
                if ((object.ReferenceEquals(this.data_fField, value) != true)) {
                    this.data_fField = value;
                    this.RaisePropertyChanged("data_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_i {
            get {
                return this.data_iField;
            }
            set {
                if ((object.ReferenceEquals(this.data_iField, value) != true)) {
                    this.data_iField = value;
                    this.RaisePropertyChanged("data_i");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Event.Evento evento {
            get {
                return this.eventoField;
            }
            set {
                if ((object.ReferenceEquals(this.eventoField, value) != true)) {
                    this.eventoField = value;
                    this.RaisePropertyChanged("evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Event.Luogo luogo {
            get {
                return this.luogoField;
            }
            set {
                if ((object.ReferenceEquals(this.luogoField, value) != true)) {
                    this.luogoField = value;
                    this.RaisePropertyChanged("luogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_f {
            get {
                return this.ora_fField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_fField, value) != true)) {
                    this.ora_fField = value;
                    this.RaisePropertyChanged("ora_f");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ora_i {
            get {
                return this.ora_iField;
            }
            set {
                if ((object.ReferenceEquals(this.ora_iField, value) != true)) {
                    this.ora_iField = value;
                    this.RaisePropertyChanged("ora_i");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Evento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Event.Associazione assField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int min_vField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEv {
            get {
                return this.IdEvField;
            }
            set {
                if ((this.IdEvField.Equals(value) != true)) {
                    this.IdEvField = value;
                    this.RaisePropertyChanged("IdEv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Event.Associazione ass {
            get {
                return this.assField;
            }
            set {
                if ((object.ReferenceEquals(this.assField, value) != true)) {
                    this.assField = value;
                    this.RaisePropertyChanged("ass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.descrizioneField, value) != true)) {
                    this.descrizioneField = value;
                    this.RaisePropertyChanged("descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_p {
            get {
                return this.max_pField;
            }
            set {
                if ((this.max_pField.Equals(value) != true)) {
                    this.max_pField = value;
                    this.RaisePropertyChanged("max_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_v {
            get {
                return this.max_vField;
            }
            set {
                if ((this.max_vField.Equals(value) != true)) {
                    this.max_vField = value;
                    this.RaisePropertyChanged("max_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_p {
            get {
                return this.min_pField;
            }
            set {
                if ((this.min_pField.Equals(value) != true)) {
                    this.min_pField = value;
                    this.RaisePropertyChanged("min_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_v {
            get {
                return this.min_vField;
            }
            set {
                if ((this.min_vField.Equals(value) != true)) {
                    this.min_vField = value;
                    this.RaisePropertyChanged("min_v");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipologia {
            get {
                return this.tipologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipologiaField, value) != true)) {
                    this.tipologiaField = value;
                    this.RaisePropertyChanged("tipologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Luogo", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Luogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLuogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLuogo {
            get {
                return this.IdLuogoField;
            }
            set {
                if ((this.IdLuogoField.Equals(value) != true)) {
                    this.IdLuogoField = value;
                    this.RaisePropertyChanged("IdLuogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associazione", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Associazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string viaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAss {
            get {
                return this.IdAssField;
            }
            set {
                if ((this.IdAssField.Equals(value) != true)) {
                    this.IdAssField = value;
                    this.RaisePropertyChanged("IdAss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string via {
            get {
                return this.viaField;
            }
            set {
                if ((object.ReferenceEquals(this.viaField, value) != true)) {
                    this.viaField = value;
                    this.RaisePropertyChanged("via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Studente", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf.Classi")]
    [System.SerializableAttribute()]
    public partial class Studente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdStudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_nField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instagramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazionalitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdStud {
            get {
                return this.IdStudField;
            }
            set {
                if ((this.IdStudField.Equals(value) != true)) {
                    this.IdStudField = value;
                    this.RaisePropertyChanged("IdStud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_n {
            get {
                return this.data_nField;
            }
            set {
                if ((object.ReferenceEquals(this.data_nField, value) != true)) {
                    this.data_nField = value;
                    this.RaisePropertyChanged("data_n");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facebook {
            get {
                return this.facebookField;
            }
            set {
                if ((object.ReferenceEquals(this.facebookField, value) != true)) {
                    this.facebookField = value;
                    this.RaisePropertyChanged("facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instagram {
            get {
                return this.instagramField;
            }
            set {
                if ((object.ReferenceEquals(this.instagramField, value) != true)) {
                    this.instagramField = value;
                    this.RaisePropertyChanged("instagram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazionalita {
            get {
                return this.nazionalitaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazionalitaField, value) != true)) {
                    this.nazionalitaField = value;
                    this.RaisePropertyChanged("nazionalita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Volontario", Namespace="http://schemas.datacontract.org/2004/07/Admin_wcf")]
    [System.SerializableAttribute()]
    public partial class Volontario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVolontField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ErasEasyLife.Event.Associazione assField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_iscrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_nField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ruoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVolont {
            get {
                return this.IdVolontField;
            }
            set {
                if ((this.IdVolontField.Equals(value) != true)) {
                    this.IdVolontField = value;
                    this.RaisePropertyChanged("IdVolont");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ErasEasyLife.Event.Associazione ass {
            get {
                return this.assField;
            }
            set {
                if ((object.ReferenceEquals(this.assField, value) != true)) {
                    this.assField = value;
                    this.RaisePropertyChanged("ass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_iscr {
            get {
                return this.data_iscrField;
            }
            set {
                if ((object.ReferenceEquals(this.data_iscrField, value) != true)) {
                    this.data_iscrField = value;
                    this.RaisePropertyChanged("data_iscr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_n {
            get {
                return this.data_nField;
            }
            set {
                if ((object.ReferenceEquals(this.data_nField, value) != true)) {
                    this.data_nField = value;
                    this.RaisePropertyChanged("data_n");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruolo {
            get {
                return this.ruoloField;
            }
            set {
                if ((object.ReferenceEquals(this.ruoloField, value) != true)) {
                    this.ruoloField = value;
                    this.RaisePropertyChanged("ruolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Event.IEvent")]
    public interface IEvent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Show_events", ReplyAction="http://tempuri.org/IEvent/Show_eventsResponse")]
        System.Collections.Generic.List<ErasEasyLife.Event.Svolgimento> Show_events(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Show_events", ReplyAction="http://tempuri.org/IEvent/Show_eventsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ErasEasyLife.Event.Svolgimento>> Show_eventsAsync(string cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Get_event_by_id", ReplyAction="http://tempuri.org/IEvent/Get_event_by_idResponse")]
        ErasEasyLife.Event.Svolgimento Get_event_by_id(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Get_event_by_id", ReplyAction="http://tempuri.org/IEvent/Get_event_by_idResponse")]
        System.Threading.Tasks.Task<ErasEasyLife.Event.Svolgimento> Get_event_by_idAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Event_partecipations", ReplyAction="http://tempuri.org/IEvent/Event_partecipationsResponse")]
        System.Collections.Generic.List<ErasEasyLife.Event.Studente> Event_partecipations(ErasEasyLife.Event.Svolgimento e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Event_partecipations", ReplyAction="http://tempuri.org/IEvent/Event_partecipationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ErasEasyLife.Event.Studente>> Event_partecipationsAsync(ErasEasyLife.Event.Svolgimento e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Event_volunteers", ReplyAction="http://tempuri.org/IEvent/Event_volunteersResponse")]
        System.Collections.Generic.List<ErasEasyLife.Event.Volontario> Event_volunteers(ErasEasyLife.Event.Svolgimento e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Event_volunteers", ReplyAction="http://tempuri.org/IEvent/Event_volunteersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ErasEasyLife.Event.Volontario>> Event_volunteersAsync(ErasEasyLife.Event.Svolgimento e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Edit_Event", ReplyAction="http://tempuri.org/IEvent/Edit_EventResponse")]
        bool Edit_Event(ErasEasyLife.Event.Svolgimento s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Edit_Event", ReplyAction="http://tempuri.org/IEvent/Edit_EventResponse")]
        System.Threading.Tasks.Task<bool> Edit_EventAsync(ErasEasyLife.Event.Svolgimento s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Delete_Event", ReplyAction="http://tempuri.org/IEvent/Delete_EventResponse")]
        bool Delete_Event(ErasEasyLife.Event.Svolgimento s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Delete_Event", ReplyAction="http://tempuri.org/IEvent/Delete_EventResponse")]
        System.Threading.Tasks.Task<bool> Delete_EventAsync(ErasEasyLife.Event.Svolgimento s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Send_Email", ReplyAction="http://tempuri.org/IEvent/Send_EmailResponse")]
        void Send_Email(string nome, string email, string body_message, string sub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Send_Email", ReplyAction="http://tempuri.org/IEvent/Send_EmailResponse")]
        System.Threading.Tasks.Task Send_EmailAsync(string nome, string email, string body_message, string sub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Generate_id_Luogo", ReplyAction="http://tempuri.org/IEvent/Generate_id_LuogoResponse")]
        int Generate_id_Luogo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Generate_id_Luogo", ReplyAction="http://tempuri.org/IEvent/Generate_id_LuogoResponse")]
        System.Threading.Tasks.Task<int> Generate_id_LuogoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Generate_id", ReplyAction="http://tempuri.org/IEvent/Generate_idResponse")]
        int Generate_id();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvent/Generate_id", ReplyAction="http://tempuri.org/IEvent/Generate_idResponse")]
        System.Threading.Tasks.Task<int> Generate_idAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventChannel : ErasEasyLife.Event.IEvent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventClient : System.ServiceModel.ClientBase<ErasEasyLife.Event.IEvent>, ErasEasyLife.Event.IEvent {
        
        public EventClient() {
        }
        
        public EventClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ErasEasyLife.Event.Svolgimento> Show_events(string cond) {
            return base.Channel.Show_events(cond);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ErasEasyLife.Event.Svolgimento>> Show_eventsAsync(string cond) {
            return base.Channel.Show_eventsAsync(cond);
        }
        
        public ErasEasyLife.Event.Svolgimento Get_event_by_id(int id) {
            return base.Channel.Get_event_by_id(id);
        }
        
        public System.Threading.Tasks.Task<ErasEasyLife.Event.Svolgimento> Get_event_by_idAsync(int id) {
            return base.Channel.Get_event_by_idAsync(id);
        }
        
        public System.Collections.Generic.List<ErasEasyLife.Event.Studente> Event_partecipations(ErasEasyLife.Event.Svolgimento e) {
            return base.Channel.Event_partecipations(e);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ErasEasyLife.Event.Studente>> Event_partecipationsAsync(ErasEasyLife.Event.Svolgimento e) {
            return base.Channel.Event_partecipationsAsync(e);
        }
        
        public System.Collections.Generic.List<ErasEasyLife.Event.Volontario> Event_volunteers(ErasEasyLife.Event.Svolgimento e) {
            return base.Channel.Event_volunteers(e);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ErasEasyLife.Event.Volontario>> Event_volunteersAsync(ErasEasyLife.Event.Svolgimento e) {
            return base.Channel.Event_volunteersAsync(e);
        }
        
        public bool Edit_Event(ErasEasyLife.Event.Svolgimento s) {
            return base.Channel.Edit_Event(s);
        }
        
        public System.Threading.Tasks.Task<bool> Edit_EventAsync(ErasEasyLife.Event.Svolgimento s) {
            return base.Channel.Edit_EventAsync(s);
        }
        
        public bool Delete_Event(ErasEasyLife.Event.Svolgimento s) {
            return base.Channel.Delete_Event(s);
        }
        
        public System.Threading.Tasks.Task<bool> Delete_EventAsync(ErasEasyLife.Event.Svolgimento s) {
            return base.Channel.Delete_EventAsync(s);
        }
        
        public void Send_Email(string nome, string email, string body_message, string sub) {
            base.Channel.Send_Email(nome, email, body_message, sub);
        }
        
        public System.Threading.Tasks.Task Send_EmailAsync(string nome, string email, string body_message, string sub) {
            return base.Channel.Send_EmailAsync(nome, email, body_message, sub);
        }
        
        public int Generate_id_Luogo() {
            return base.Channel.Generate_id_Luogo();
        }
        
        public System.Threading.Tasks.Task<int> Generate_id_LuogoAsync() {
            return base.Channel.Generate_id_LuogoAsync();
        }
        
        public int Generate_id() {
            return base.Channel.Generate_id();
        }
        
        public System.Threading.Tasks.Task<int> Generate_idAsync() {
            return base.Channel.Generate_idAsync();
        }
    }
}
